-- 1. Crear la base de datos (Ejecutar por separado si es necesario)
-- CREATE DATABASE proyecto_wyk;

-- 2. Definición de tipos ENUM (Postgres requiere crearlos primero)
CREATE TYPE tipo_clasificacion AS ENUM ('EMPLEADO', 'ADMINISTRADOR');
CREATE TYPE tipo_prioridad AS ENUM ('BAJA', 'MEDIA', 'ALTA');
CREATE TYPE tipo_estado_tarea AS ENUM ('PENDIENTE', 'COMPLETADA', 'CANCELADA');
CREATE TYPE tipo_producto AS ENUM ('PANADERIA', 'PASTELERIA', 'ASEO');
CREATE TYPE tipo_estado_pedido AS ENUM ('PENDIENTE', 'PREPARANDO', 'ENTREGADO', 'CANCELADO');
CREATE TYPE tipo_estado_pago AS ENUM ('PENDIENTE', 'PAGADA', 'CANCELADA');
CREATE TYPE tipo_ajuste AS ENUM ('DAÑADO', 'ROBO', 'PERDIDA', 'CADUCADO', 'MUESTRA');
CREATE TYPE tipo_ajuste_mat AS ENUM ('DAÑADO', 'ROBO', 'PERDIDA', 'CADUCADO');
CREATE TYPE tipo_compra AS ENUM ('MATERIA PRIMA', 'PRODUCTO TERMINADO');
CREATE TYPE tipo_estado_produccion AS ENUM ('PENDIENTE', 'EN_PROCESO', 'FINALIZADA', 'CANCELADA');

-- 3. Creación de tablas
CREATE TABLE ROL (
    ID_ROL SERIAL PRIMARY KEY,
    ROL VARCHAR(50) NOT NULL,
    CLASIFICACION tipo_clasificacion NOT NULL,
    ESTADO_ROL BOOLEAN NOT NULL
);

CREATE TABLE USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NUM_DOC BIGINT UNIQUE NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    PASSWORD_USUARIO VARCHAR(150) NOT NULL,
    TEL_USUARIO BIGINT NOT NULL,
    EMAIL_USUARIO VARCHAR(50) UNIQUE NOT NULL,
    FECHA_REGISTRO TIMESTAMP NOT NULL,
    ROL_FK_USUARIO INT NOT NULL,
    ESTADO_USUARIO BOOLEAN NOT NULL,
    CONSTRAINT ROL_FK_USUARIO FOREIGN KEY (ROL_FK_USUARIO) REFERENCES ROL (ID_ROL)
);

CREATE TABLE TAREA (
    ID_TAREA SERIAL PRIMARY KEY,
    TAREA VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(80) NOT NULL,
    DESCRIPCION VARCHAR(250) NULL,
    TIEMPO_ESTIMADO_HORAS REAL NOT NULL,
    PRIORIDAD tipo_prioridad,
    ESTADO_TAREA tipo_estado_tarea,
    USUARIO_ASIGNADO_FK INT NOT NULL,
    USUARIO_CREADOR_FK INT NOT NULL,
    CONSTRAINT USUARIO_ASIGNADO_FK FOREIGN KEY(USUARIO_ASIGNADO_FK) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT USUARIO_CREADOR_FK FOREIGN KEY(USUARIO_CREADOR_FK) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO BIGINT PRIMARY KEY NOT NULL, -- Aquí no hay serial porque en tu origen no tenía auto_increment
    NOMBRE_PRODUCTO VARCHAR(50) UNIQUE NOT NULL,
    VALOR_UNITARIO_PRODUCTO BIGINT NOT NULL,
    CANT_EXIST_PRODUCTO BIGINT NOT NULL,
    FECHA_VENCIMIENTO_PRODUCTO DATE NOT NULL,
    TIPO_PRODUCTO tipo_producto NOT NULL,
    ID_USUARIO_FK_PRODUCTO INT NOT NULL,
    ESTADO_PRODUCTO BOOLEAN NOT NULL,
    CONSTRAINT ID_USUARIO_FK_PRODUCTO FOREIGN KEY (ID_USUARIO_FK_PRODUCTO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE VENTA (
    ID_VENTA BIGSERIAL PRIMARY KEY,
    FECHA_HORA_VENTA TIMESTAMP NOT NULL,
    TOTAL_VENTA BIGINT NOT NULL,
    NUMERO_MESA INT NULL,
    DESCRIPCION VARCHAR(200) NULL,
    ID_USUARIO_FK_VENTA INT NOT NULL,
    ESTADO_PEDIDO tipo_estado_pedido NOT NULL,
    ESTADO_PAGO tipo_estado_pago NOT NULL,
    CONSTRAINT ID_USUARIO_FK_VENTA FOREIGN KEY (ID_USUARIO_FK_VENTA) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE DETALLE_VENTA (
    ID_DETALLE_VENTA SERIAL PRIMARY KEY,
    CANTIDAD BIGINT NOT NULL,
    SUB_TOTAL BIGINT NOT NULL,
    ID_VENTA_FK_DET_VENTA BIGINT NOT NULL,
    ID_PRODUCTO_FK_DET_VENTA BIGINT NOT NULL,
    CONSTRAINT ID_VENTA_FK_DET_VENTA FOREIGN KEY (ID_VENTA_FK_DET_VENTA) REFERENCES VENTA (ID_VENTA),
    CONSTRAINT ID_PRODUCTO_FK_DET_VENTA FOREIGN KEY (ID_PRODUCTO_FK_DET_VENTA) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE AJUSTE_INVENTARIO (
    ID_AJUSTE SERIAL PRIMARY KEY,
    FECHA_AJUSTE TIMESTAMP NOT NULL,
    TIPO_AJUSTE tipo_ajuste NOT NULL,
    CANTIDAD_AJUSTADA INT NOT NULL,
    DESCRIPCION VARCHAR(200) NULL,
    ID_PROD_FK_AJUSTE_INVENTARIO BIGINT NOT NULL,
    ID_USUARIO_FK_AJUSTE_INVENTARIO INT NOT NULL,
    CONSTRAINT ID_PROD_FK_AJUSTE_INVENTARIO FOREIGN KEY (ID_PROD_FK_AJUSTE_INVENTARIO) REFERENCES PRODUCTO (ID_PRODUCTO),
    CONSTRAINT ID_USUARIO_FK_AJUSTE_INVENTARIO FOREIGN KEY (ID_USUARIO_FK_AJUSTE_INVENTARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE MATERIA_PRIMA (
    ID_MATERIA_PRIMA BIGSERIAL PRIMARY KEY,
    NOMBRE_MATERIA_PRIMA VARCHAR(50) NOT NULL,
    VALOR_UNITARIO_MAT_PRIMA BIGINT NOT NULL,
    FECHA_VENCIMIENTO_MATERIA_PRIMA DATE NOT NULL,
    CANTIDAD_EXIST_MATERIA_PRIMA BIGINT NOT NULL,
    PRESENTACION_MATERIA_PRIMA VARCHAR(50) NOT NULL,
    DESCRIPCION_MATERIA_PRIMA VARCHAR(200) NOT NULL,
    ID_USUARIO_FK_MATERIA_PRIMA INT NOT NULL,
    ESTADO_MATERIA_PRIMA BOOLEAN NOT NULL,
    CONSTRAINT ID_USUARIO_FK_MATERIA_PRIMA FOREIGN KEY (ID_USUARIO_FK_MATERIA_PRIMA) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE AJUSTE_MATERIA_PRIMA (
	ID_AJUS_MAT SERIAL PRIMARY KEY,
	FECHA_AJUS_MAT TIMESTAMP NOT NULL,
	TIPO_AJUS_MAT tipo_ajuste_mat NOT NULL,
	CANTIDAD_AJUSTADA_MAT INT NOT NULL,
	ID_MAT_FK_AJUSTE_MAT  BIGINT NOT NULL,
	ID_USUARIO_FK_AJUSTE_MAT INT NOT NULL,
	CONSTRAINT ID_MAT_FK_AJUSTE_MAT FOREIGN KEY (ID_MAT_FK_AJUSTE_MAT) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA),
	CONSTRAINT ID_USUARIO_FK_AJUSTE_MAT FOREIGN KEY (ID_USUARIO_FK_AJUSTE_MAT) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE COMPRA (
    ID_COMPRA BIGSERIAL PRIMARY KEY,
    FECHA_HORA_COMPRA TIMESTAMP NOT NULL,
    TIPO tipo_compra,
    TOTAL_COMPRA BIGINT NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR(50) NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    TEL_PROVEEDOR BIGINT UNIQUE NOT NULL,
    EMAIL_PROVEEDOR VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPCION_COMPRA VARCHAR(200) NULL,
    ID_USUARIO_FK_COMPRA INT NOT NULL,
    ESTADO_FACTURA_COMPRA tipo_estado_pago NOT NULL, -- Reusamos tipo_estado_pago ya que tiene los mismos valores
    CONSTRAINT ID_USUARIO_FK_COMPRA FOREIGN KEY (ID_USUARIO_FK_COMPRA) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE DETALLE_COMPRA_MATERIA_PRIMA (
    ID_DET_COMPRA_MAT_PRIM SERIAL PRIMARY KEY,
    CANTIDAD_MAT_PRIMA_COMPRADA BIGINT NOT NULL,
    SUB_TOTAL_MAT_PRIMA_COMPRADA BIGINT NOT NULL,
    ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA BIGINT NOT NULL,
    ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA BIGINT NOT NULL,
    ESTADO_DET_COMPRA_MAT_PRIMA BOOLEAN NOT NULL,
    CONSTRAINT ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA FOREIGN KEY (ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA) REFERENCES COMPRA (ID_COMPRA),
    CONSTRAINT ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA FOREIGN KEY (ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA)
);

CREATE TABLE DETALLE_COMPRA_PRODUCTO (
    ID_DET_COMPRA_PROD SERIAL PRIMARY KEY,
    CANTIDAD_PROD_COMPRADO BIGINT NOT NULL,
    SUB_TOTAL_PROD_COMPRADO BIGINT NOT NULL,
    ID_COMPRA_FK_DET_COMPRA_PROD BIGINT NOT NULL,
    ID_PROD_FK_DET_COMPRA_PROD BIGINT NOT NULL,
    ESTADO_DET_COMPRA_PROD BOOLEAN NOT NULL,
    CONSTRAINT ID_COMPRA_FK_DET_COMPRA_PROD FOREIGN KEY (ID_COMPRA_FK_DET_COMPRA_PROD) REFERENCES COMPRA (ID_COMPRA),
    CONSTRAINT ID_PROD_FK_DET_COMPRA_PROD FOREIGN KEY (ID_PROD_FK_DET_COMPRA_PROD) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE PRODUCCION (
    ID_PRODUCCION BIGSERIAL PRIMARY KEY,
    NOMBRE_PRODUCCION VARCHAR(50) NOT NULL,
	CATEGORIA_PRODUCCION VARCHAR(50) NOT NULL,
    CANT_PRODUCCION BIGINT NOT NULL,
    DESCRIPCION_PRODUCCION VARCHAR(200) NOT NULL,
    ID_PRODUCTO_FK_PRODUCCION BIGINT NOT NULL,
    ID_USUARIO_FK_PRODUCCION INT NOT NULL,
    ESTADO_PRODUCCION tipo_estado_produccion NOT NULL,
    CONSTRAINT ID_PRODUCTO_FK_PRODUCCION FOREIGN KEY (ID_PRODUCTO_FK_PRODUCCION) REFERENCES PRODUCTO (ID_PRODUCTO),
    CONSTRAINT ID_USUARIO_FK_PRODUCCION FOREIGN KEY (ID_USUARIO_FK_PRODUCCION) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE DETALLE_PRODUCCION (
    ID_DETALLE_PRODUCCION BIGSERIAL PRIMARY KEY,
    ID_PRODUCCION_FK_DET_PRODUC BIGINT NOT NULL,
    ID_MATERIA_PRIMA_FK_DET_PRODUC  BIGINT NOT NULL,
    CANTIDAD_REQUERIDA DECIMAL(10,2) NOT NULL,
    CONSTRAINT ID_PRODUCCION_FK_DET_PRODUC FOREIGN KEY (ID_PRODUCCION_FK_DET_PRODUC) REFERENCES PRODUCCION(ID_PRODUCCION),
    CONSTRAINT ID_MATERIA_PRIMA_FK_DET_PRODUC FOREIGN KEY (ID_MATERIA_PRIMA_FK_DET_PRODUC) REFERENCES MATERIA_PRIMA(ID_MATERIA_PRIMA)
);