# Generated by Django 6.0.2 on 2026-07-30 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProduccion',
            fields=[
                ('id_detalle_produccion', models.BigAutoField(db_column='id_detalle_produccion', primary_key=True, serialize=False)),
                ('cantidad_requerida', models.DecimalField(db_column='cantidad_requerida', decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenAbastecimiento',
            fields=[
                ('id_orden_abastecimiento', models.BigAutoField(db_column='id_orden_abastecimiento', primary_key=True, serialize=False)),
                ('fecha_hora_registro', models.DateTimeField(db_column='fecha_hora_registro', default=django.utils.timezone.now)),
                ('tipo_orden', models.CharField(choices=[('PRODUCCION', 'PRODUCCION'), ('COMPRA', 'COMPRA')], db_column='tipo_orden', max_length=20)),
                ('origen_orden', models.CharField(choices=[('FALTANTE_VENTA', 'FALTANTE_VENTA'), ('PREVENTIVO_VENTA', 'PREVENTIVO_VENTA'), ('MANUAL_DIRECTO', 'MANUAL_DIRECTO')], db_column='origen_orden', max_length=20)),
                ('observacion', models.CharField(blank=True, db_column='observacion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'orden_abastecimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id_produccion', models.BigAutoField(db_column='id_produccion', primary_key=True, serialize=False)),
                ('nombre_produccion', models.CharField(db_column='nombre_produccion', max_length=50)),
                ('fecha_hora_produccion', models.DateTimeField(db_column='fecha_hora_produccion')),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, db_column='fecha_cambio_estado', null=True)),
                ('categoria_produccion', models.CharField(db_column='categoria_produccion', max_length=50)),
                ('cant_produccion', models.BigIntegerField(db_column='cant_produccion')),
                ('descripcion_produccion', models.CharField(db_column='descripcion_produccion', max_length=200)),
                ('estado_produccion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_column='estado_produccion', max_length=20)),
            ],
            options={
                'db_table': 'produccion',
                'managed': False,
            },
        ),
    ]
